### ISSUE TITLE
ng-model 数据绑定问题

### ISSUE THREAD

**Issue by aaa641521** [wanming/angular-editor#10]
刚接触 angular 不久，遇到这样一个问题：
页面加载完成后 通过异步加载 添加 ng-repeat 集合中数据 生成新的 input ng-model="phoneNum" 绑定，在页面 处使用 {{name}} 可以 正常实现动态绑定 ，但在controller 中 $scope.name 却始终为空，这是什么问题，集合中只有一个 input ng-model="phoneNum" 。
![image](https://cloud.githubusercontent.com/assets/11342787/6613355/66c3bd20-c8c6-11e4-8b26-f43a8cfedc43.png)
![image](https://cloud.githubusercontent.com/assets/11342787/6613381/d925dbf0-c8c6-11e4-9229-596ce46ba4c6.png)
controller 中 $scope.phoneNum 始终为空

**Comment by wanming** [comment]
能否发个jsfiddle出来，提供的信息有点少

**Comment by nishantkumarverma** [comment]
not working on ng-model change
