### ISSUE TITLE
编辑器中“source”按钮的查看源代码功能无法使用

### ISSUE THREAD

**Issue by cong5** [wanming/angular-editor#11]
编辑器中如果添加“source”按钮，来开启查看源代码功能，但是点击后是空白的，没有出现源代码，请问这个问题怎么解决。
编辑器的插件里面好像写是返回到texearea标签里面的，但是angular里面使用的却是一个div了

**Comment by wanming** [comment]
感觉支持，这个版本的编辑器只支持title,bold,italic,underline,ol,ul,blockquote,code,link,image,indent,outdent,hr,table,strikethrough这些类型，你是用了最新的simeditor才出现这个问题的吗？

**Comment by Cong5** [comment]
嗯，是的。是最新的编辑器。

**Comment by Cong5** [comment]
关于查看源代码无法使用的这个，有解决方法或者建议吗？
